checking husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,16 +1,10 @@
 #!/bin/bash
 
-echo "Checking for changes in web/src..."
-if git diff --name-only @{push}...HEAD | grep -q 'web/src'; then
-  echo "Changes detected in web/src since the last push. Running npm run build to ensure the project builds successfully..."
-  echo "Linting files..."
-  cd web
-  if npx lint-staged; then
-    echo "Linting files... Done"
-  else
-    echo "Linting failed. Please fix the errors and try again."
-    exit 1
-  fi
+echo "Running lint check on pre-commit..."
+cd web
+if npx lint-staged; then
+  echo "Linting successful. Proceeding with commit..."
 else
-  echo "No changes detected in web/src since the last push. Skipping build..."
+  echo "Linting failed. Please fix the errors and try again."
+  exit 1
 fi
